[build]
  command = "npm run build"
  commandOrigin: config
  environment:
    - NEXT_PUBLIC_APP_URL
  publish: /opt/build/repo/.next
  publishOrigin: config
[[plugins]]
  - inputs: {}
    origin: config
    package: '@netlify/plugin-nextjs
