backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "profile"
    label: "Profile Info"
    files:
      - label: "Home Section"
        name: "home"
        file: "index-admin.html"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
